#!/bin/bash
#SBATCH -p RM-shared
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 36:00:00
#SBATCH --mail-type=ALL
#SBATCH --array=1-706
VAR=$((SLURM_ARRAY_TASK_ID))
echo $VAR

VARIABLE=$(head -"$VAR" bash/collide1.txt | tail -1)
echo $VARIABLE
stringarray=($VARIABLE)

module load python
module load anaconda3
conda activate hrt-funs

python optimize_pvals_cont.py --label  ${stringarray[0]} --X_target ${stringarray[1]} --Y_target ${stringarray[2]}  --NUM_EPOCHS 1000 --stop_pval 0.8 --model_type mlp 